[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-multipart = "0.7.2"
actix-web = "4.9.0"
futures = "0.3.31"
image = "0.25.5"
serde_json = "1.0.138"
